services:
  db:
    image: mysql:latest
    container_name: db_forumhub_dev
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_forumhub_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: devdatabase1234
    volumes:
      - db_data:/var/lib/mysql
      - $PWD/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
